# Generated by Django 6.1 on 2026-08-30 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bornes', '0001_initial'),
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echoue', 'Échoué')], default='en_attente', max_length=20, verbose_name='statut')),
                ('trade_no', models.CharField(blank=True, help_text='Conservé pour interroger printStatus depuis la console.', max_length=100, verbose_name='numéro Sunmi')),
                ('tentatives', models.PositiveIntegerField(default=0, verbose_name='tentatives')),
                ('message_erreur', models.TextField(blank=True, verbose_name='erreur')),
                ('creee_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_impression', to='bornes.borne')),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_impression', to='capsules.capsule')),
            ],
            options={
                'verbose_name': "job d'impression",
                'verbose_name_plural': "jobs d'impression",
                'ordering': ['-creee_le'],
            },
        ),
    ]
