# Generated by Django 6.1 on 2026-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Ce que le QR code de l'affiche encode : /b/<slug>", unique=True, verbose_name="identifiant d'URL")),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('numero_serie_imprimante', models.CharField(blank=True, help_text="Le SN Sunmi de l'imprimante posée à côté de l'affiche.", max_length=100, verbose_name="numéro de série de l'imprimante")),
                ('dots_par_ligne', models.PositiveIntegerField(default=576, help_text='576 pour du papier 80 mm, 384 pour du 58 mm.', verbose_name='points par ligne')),
                ('active', models.BooleanField(default=True, help_text="Décochée, la borne n'accepte plus d'enregistrement.", verbose_name='active')),
                ('texte_accueil', models.TextField(blank=True, help_text='La phrase que lit le visiteur en arrivant sur la page.', verbose_name="texte d'accueil")),
                ('duree_max_secondes', models.PositiveIntegerField(default=600, help_text="Garde-fou contre l'enregistrement oublié en poche.", verbose_name='durée maximale en secondes')),
                ('creee_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
            ],
            options={
                'verbose_name': 'borne',
                'verbose_name_plural': 'bornes',
                'ordering': ['nom'],
            },
        ),
    ]
