# Generated by Django 6.1 on 2026-09-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bornes', '0003_reglages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglages',
            name='duree_max_secondes',
        ),
    ]
