# Generated by Django 6.1 on 2026-08-30 22:39

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

import capsules.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bornes', '0001_initial'),
    ]

    operations = [
        # L'EXTENSION D'ABORD : sans elle, le VectorField ne peut pas
        # etre cree et la migration echoue sur une table vide.
        # / The extension must come first, or VectorField cannot be created.
        VectorExtension(),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'tag',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pseudo', models.CharField(blank=True, max_length=80, verbose_name='pseudo')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('retiree', 'Retirée')], default='brouillon', max_length=20, verbose_name='statut')),
                ('audio_original', models.FileField(upload_to=capsules.models.chemin_audio_original, verbose_name='audio original')),
                ('audio_diffusion', models.FileField(blank=True, help_text='AAC/m4a : le seul format lu par tous les navigateurs.', upload_to=capsules.models.chemin_audio_diffusion, verbose_name='audio de diffusion')),
                ('duree_secondes', models.PositiveIntegerField(default=0, verbose_name='durée')),
                ('photo', models.ImageField(blank=True, help_text="Métadonnées EXIF purgées à l'ingestion.", null=True, upload_to=capsules.models.chemin_photo, verbose_name='photo')),
                ('creee_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('publiee_le', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('nombre_ecoutes', models.PositiveIntegerField(default=0, verbose_name='écoutes')),
                ('transcription_raw', models.JSONField(blank=True, help_text='Segments diarisés : [{speaker, start, end, text}]', null=True, verbose_name='transcription brute')),
                ('transcription_texte', models.TextField(blank=True, verbose_name='transcription')),
                ('langue_detectee', models.CharField(blank=True, max_length=10, verbose_name='langue')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True, verbose_name='vecteur')),
                ('enrichie_le', models.DateTimeField(blank=True, null=True, verbose_name='enrichie le')),
                ('erreur_enrichissement', models.TextField(blank=True, verbose_name='erreur')),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capsules', to='bornes.borne', verbose_name='borne')),
            ],
            options={
                'verbose_name': 'capsule',
                'verbose_name_plural': 'capsules',
                'ordering': ['-creee_le'],
            },
        ),
        migrations.CreateModel(
            name='TagDeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('auteur', "Saisi par l'auteur"), ('machine', 'Extrait par le modèle')], max_length=10, verbose_name='origine')),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_de_capsule', to='capsules.capsule')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='capsules.tag')),
            ],
            options={
                'verbose_name': 'tag de capsule',
                'unique_together': {('capsule', 'tag', 'origine')},
            },
        ),
    ]
