# Generated by Django 6.1 on 2026-08-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='position_x',
            field=models.FloatField(blank=True, null=True, verbose_name='position x'),
        ),
        migrations.AddField(
            model_name='capsule',
            name='position_y',
            field=models.FloatField(blank=True, null=True, verbose_name='position y'),
        ),
    ]
