# Generated by Django 6.1 on 2026-08-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bornes', '0003_reglages'),
        ('capsules', '0003_capsule_reglages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='reglages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capsules', to='bornes.reglages', verbose_name='réglages'),
        ),
    ]
