# Generated by Django 6.1 on 2026-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_alter_capsule_reglages'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='titre',
            field=models.CharField(blank=True, help_text='Déduit de la transcription par le modèle.', max_length=120, verbose_name='titre'),
        ),
    ]
