# Generated by Django 6.1 on 2026-09-11 16:55

from django.db import migrations, models

import capsules.models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_capsule_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='uuid',
            field=models.UUIDField(default=capsules.models.uuid_au_prefixe_libre, editable=False, primary_key=True, serialize=False),
        ),
    ]
