# Generated by Django 6.1 on 2026-09-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_uuid_au_prefixe_libre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grille', models.JSONField(blank=True, default=list, verbose_name='grille de densité')),
                ('regions', models.JSONField(blank=True, default=list, verbose_name='régions')),
                ('calcule_le', models.DateTimeField(blank=True, null=True, verbose_name='calculé le')),
            ],
            options={
                'verbose_name': 'ciel',
            },
        ),
    ]
